# Generated by Django 2.1.1 on 2018-09-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.FloatField()),
                ('right', models.FloatField()),
                ('top', models.FloatField()),
                ('bottom', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='road_damages.BoundingBox')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(verbose_name='date registered')),
                ('longtitiude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('photo', models.FileField(upload_to='road_images/')),
                ('damage_prediction', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road_damages.Prediction')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='registered_damage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road_damages.RegisteredDamage'),
        ),
    ]
