# Generated by Django 2.1.1 on 2018-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_damages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddamage',
            name='photo',
            field=models.ImageField(upload_to='road_images/'),
        ),
    ]
