# Generated by Django 2.1.1 on 2018-10-03 08:11

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('road_damages', '0003_auto_20180929_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddamage',
            name='register_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='date registered'),
        ),
    ]
