# Generated by Django 2.1.1 on 2018-10-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_damages', '0005_auto_20181003_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('width_x', models.IntegerField()),
                ('width_y', models.IntegerField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='road_damages.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='registereddamage',
            name='post',
        ),
    ]
