# Generated by Django 2.1.1 on 2018-10-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_damages', '0006_auto_20181003_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='width_x',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='width_y',
        ),
    ]
