# Generated by Django 2.1.1 on 2018-10-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_damages', '0007_auto_20181003_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='registereddamage',
            name='damage_prediction',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
